const outputArg = Deno.args[0] ?? 'cuebert-ai-context.zip'
const output = outputArg.startsWith('/')
  ? outputArg
  : `${Deno.cwd()}/${outputArg}`
const stagingRoot = await Deno.makeTempDir({ prefix: 'cuebert-ai-context-' })
const stagingProject = `${stagingRoot}/subtitle-editor`

const includeTopLevelFiles = new Set([
  '.gitignore',
  'README.md',
  'deno.json',
  'deno.lock',
  'compress.js',
  'submit-issues.js'
])

const includeDirectories = [
  'cuebert',
  'scripts',
  'src-tauri/capabilities',
  'src-tauri/src'
]

const includeFiles = new Set([
  'src-tauri/build.rs',
  'src-tauri/Cargo.lock',
  'src-tauri/Cargo.toml',
  'src-tauri/tauri.conf.json'
])

const includeExtensions = new Set([
  '.css',
  '.html',
  '.js',
  '.json',
  '.lock',
  '.md',
  '.rs',
  '.sh',
  '.svg',
  '.toml'
])

const excludedPathParts = new Set([
  '.git',
  '.vscode',
  'node_modules',
  'target',
  'screenshots',
  'sample-atrain-output',
  'work'
])

const excludedExtensions = new Set([
  '.app',
  '.dmg',
  '.icns',
  '.jpg',
  '.jpeg',
  '.png',
  '.webp',
  '.zip'
])

function extensionFor(path) {
  const fileName = path.split('/').pop() ?? ''
  const index = fileName.lastIndexOf('.')
  return index === -1 ? '' : fileName.slice(index).toLowerCase()
}

function hasExcludedPart(path) {
  return path.split('/').some(part => excludedPathParts.has(part))
}

function shouldInclude(path) {
  if (hasExcludedPart(path)) return false
  if (includeTopLevelFiles.has(path) || includeFiles.has(path)) return true
  if (!includeDirectories.some(directory => path === directory || path.startsWith(`${directory}/`))) {
    return false
  }

  const extension = extensionFor(path)
  return includeExtensions.has(extension) && !excludedExtensions.has(extension)
}

async function collectFiles(directory = '.') {
  const files = []

  for await (const entry of Deno.readDir(directory)) {
    const path = directory === '.' ? entry.name : `${directory}/${entry.name}`
    if (hasExcludedPart(path)) continue
    if (entry.isDirectory) {
      files.push(...await collectFiles(path))
    } else if (entry.isFile && shouldInclude(path)) {
      files.push(path)
    }
  }

  return files.sort()
}

async function ensureParentDirectory(path) {
  const index = path.lastIndexOf('/')
  if (index === -1) return
  await Deno.mkdir(path.slice(0, index), { recursive: true })
}

async function copyIntoStaging(path) {
  const target = `${stagingProject}/${path}`
  await ensureParentDirectory(target)
  await Deno.copyFile(path, target)
}

async function runText(command, args) {
  const result = await new Deno.Command(command, {
    args,
    stdout: 'piped',
    stderr: 'piped'
  }).output()

  const decoder = new TextDecoder()
  const stdout = decoder.decode(result.stdout).trim()
  const stderr = decoder.decode(result.stderr).trim()
  return result.code === 0
    ? stdout
    : `${stdout}\n${stderr}`.trim()
}

async function writeManifest(files) {
  const [status, branch, diffStat] = await Promise.all([
    runText('git', ['status', '--short']),
    runText('git', ['branch', '--show-current']),
    runText('git', ['diff', '--stat'])
  ])

  const contents = `# Cuebert AI Context

Generated by \`deno task context:zip\`.

## Branch

\`\`\`
${branch || '(unknown)'}
\`\`\`

## Git Status

\`\`\`
${status || '(clean)'}
\`\`\`

## Diff Stat

\`\`\`
${diffStat || '(no unstaged diff)'}
\`\`\`

## Included Files

${files.map(file => `- ${file}`).join('\n')}
`

  await Deno.writeTextFile(`${stagingProject}/AI_CONTEXT.md`, contents)
}

async function removeIfExists(path) {
  try {
    await Deno.remove(path)
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error
  }
}

const files = await collectFiles()
await Deno.mkdir(stagingProject, { recursive: true })

for (const file of files) {
  await copyIntoStaging(file)
}

await writeManifest(files)
await removeIfExists(output)

const zip = new Deno.Command('zip', {
  args: ['-qr', output, 'subtitle-editor'],
  cwd: stagingRoot,
  stdout: 'inherit',
  stderr: 'inherit'
})
const { code } = await zip.output()

if (code !== 0) {
  console.error(`zip failed with exit code ${code}`)
  Deno.exit(code)
}

await Deno.remove(stagingRoot, { recursive: true })
console.log(`Created ${output} with ${files.length + 1} files`)
